language: node_js

node_js:
  - "5.3"

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp config/database.js.travis config/database.js
  - psql -c 'create database developers_brasil_test;' -U postgres

script:
  - npm run lint
  - npm test
  - npm run coveralls
